"""add phase column to entries

Revision ID: 167ece6819ff
Revises: f68d619b7fe8
Create Date: 2026-07-27 19:28:43.926550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '167ece6819ff'
down_revision: Union[str, Sequence[str], None] = 'f68d619b7fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('phase', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'phase')
    # ### end Alembic commands ###
