"""add_asset_link_to_entries

Revision ID: a8dd0fa6bfe7
Revises: 167ece6819ff
Create Date: 2026-07-27 21:50:32.858805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8dd0fa6bfe7'
down_revision: Union[str, Sequence[str], None] = '167ece6819ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_tags_id'), table_name='entry_tags')
    op.drop_table('entry_tags')
    op.add_column('entries', sa.Column('asset_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'asset_link')
    op.create_table('entry_tags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('entry_id', sa.INTEGER(), nullable=False),
    sa.Column('tag_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_tags_id'), 'entry_tags', ['id'], unique=False)
    # ### end Alembic commands ###
